//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AMS_Event
    {
        public AMS_Event()
        {
            this.AMS_Event_Daily = new HashSet<AMS_Event_Daily>();
            this.AMS_Event_Latest = new HashSet<AMS_Event_Latest>();
            this.AMS_RishMaster_Group = new HashSet<AMS_RishMaster_Group>();
        }
    
        public int Id { get; set; }
        public System.DateTime EventDateTime { get; set; }
        public string SiteId { get; set; }
    
        public virtual ICollection<AMS_Event_Daily> AMS_Event_Daily { get; set; }
        public virtual ICollection<AMS_Event_Latest> AMS_Event_Latest { get; set; }
        public virtual ICollection<AMS_RishMaster_Group> AMS_RishMaster_Group { get; set; }
    }
}
