//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DemoUnit_LatestEvent
    {
        public int Id { get; set; }
        public int DemoUnit_EventId { get; set; }
        public System.DateTime EventDateTime { get; set; }
        public string SiteId { get; set; }
    
        public virtual DemoUnit_Event DemoUnit_Event { get; set; }
    }
}
