//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DemoUnit_Event
    {
        public DemoUnit_Event()
        {
            this.DemoUnit_LatestEvent = new HashSet<DemoUnit_LatestEvent>();
        }
    
        public int Id { get; set; }
        public string SiteId { get; set; }
        public System.DateTime EventDateTime { get; set; }
        public int RishMasterEventId { get; set; }
        public decimal Sensor1 { get; set; }
        public decimal Sensor2 { get; set; }
        public decimal Sensor3 { get; set; }
        public decimal Sensor4 { get; set; }
        public decimal Sensor5 { get; set; }
        public decimal Sensor6 { get; set; }
        public decimal Sensor7 { get; set; }
        public decimal Sensor8 { get; set; }
        public decimal VibrationSensor { get; set; }
        public decimal LiquidTemperatureSensor { get; set; }
        public decimal AirFlowSensor { get; set; }
        public decimal WaterFlowSensor { get; set; }
    
        public virtual RishMasterEvent RishMasterEvent { get; set; }
        public virtual ICollection<DemoUnit_LatestEvent> DemoUnit_LatestEvent { get; set; }
    }
}
