//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public Event()
        {
            this.LatestEvents = new HashSet<LatestEvent>();
        }
    
        public int Id { get; set; }
        public System.DateTime EventDateTime { get; set; }
        public decimal Temperature { get; set; }
        public decimal Humidity { get; set; }
        public string SiteId { get; set; }
    
        public virtual ICollection<LatestEvent> LatestEvents { get; set; }
    }
}
