//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GPSDevice
    {
        public GPSDevice()
        {
            this.GPSDevice_Event = new HashSet<GPSDevice_Event>();
            this.GPSDevice_LatestEvent = new HashSet<GPSDevice_LatestEvent>();
        }
    
        public int Id { get; set; }
        public string GPSDeviceID { get; set; }
        public int PortNumber { get; set; }
        public string MobileNumber { get; set; }
        public bool DeviceStatus { get; set; }
    
        public virtual ICollection<GPSDevice_Event> GPSDevice_Event { get; set; }
        public virtual ICollection<GPSDevice_LatestEvent> GPSDevice_LatestEvent { get; set; }
    }
}
