//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GPSDevice_Event
    {
        public GPSDevice_Event()
        {
            this.GPSDevice_LatestEvent = new HashSet<GPSDevice_LatestEvent>();
        }
    
        public int Id { get; set; }
        public int GPSDeviceId { get; set; }
        public decimal Latitude { get; set; }
        public decimal Longitude { get; set; }
        public System.DateTime EventDateTime { get; set; }
    
        public virtual GPSDevice GPSDevice { get; set; }
        public virtual ICollection<GPSDevice_LatestEvent> GPSDevice_LatestEvent { get; set; }
    }
}
