//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RishMasterEvent
    {
        public RishMasterEvent()
        {
            this.AMS_RishMaster_Group = new HashSet<AMS_RishMaster_Group>();
            this.DemoUnit_Event = new HashSet<DemoUnit_Event>();
            this.MyAppsDemoEvents = new HashSet<MyAppsDemoEvent>();
        }
    
        public int Id { get; set; }
        public byte DeviceInstanceID { get; set; }
        public decimal RPhaseVoltage { get; set; }
        public decimal YPhaseVoltage { get; set; }
        public decimal BPhaseVoltage { get; set; }
        public decimal RPhaseCurrent { get; set; }
        public decimal YPhaseCurrent { get; set; }
        public decimal BPhaseCurrent { get; set; }
        public decimal RPhaseWattage { get; set; }
        public decimal YPhaseWattage { get; set; }
        public decimal BPhaseWattage { get; set; }
        public decimal RPhasePower { get; set; }
        public decimal YPhasePower { get; set; }
        public decimal BPhasePower { get; set; }
        public decimal RPhaseReactivePower { get; set; }
        public decimal YPhaseReactivePower { get; set; }
        public decimal BPhaseReactivePower { get; set; }
        public decimal RPhasePowerFactor { get; set; }
        public decimal YPhasePowerFactor { get; set; }
        public decimal BPhasePowerFactor { get; set; }
        public decimal RPhasePhaseAngle { get; set; }
        public decimal YPhasePhaseAngle { get; set; }
        public decimal BPhasePhaseAngle { get; set; }
        public decimal AverageVotage { get; set; }
        public decimal SumofVoltages { get; set; }
        public decimal AverageCurrent { get; set; }
        public decimal SumofCurrents { get; set; }
        public decimal AverageWatt { get; set; }
        public decimal SumofWatt { get; set; }
        public decimal AverageofPower { get; set; }
        public decimal SumofPower { get; set; }
        public decimal AverageofReactivePower { get; set; }
        public decimal SumofReactivePower { get; set; }
        public decimal AveragePowerFactor { get; set; }
        public decimal SumofPowerFactor { get; set; }
        public decimal AveragePhaseAngle { get; set; }
        public decimal SumofPhaseAngle { get; set; }
        public decimal Frequency { get; set; }
        public decimal ImportWattHours { get; set; }
        public decimal ExportWattHours { get; set; }
        public decimal ImportReactiveHours { get; set; }
        public decimal ExportReactiveHours { get; set; }
        public decimal VoltAmpereHours { get; set; }
        public decimal AvgMaximumVoltage { get; set; }
        public decimal AvgMinimumVoltage { get; set; }
        public decimal AvgMaximumCurrent { get; set; }
        public decimal AvgMinimumCurrent { get; set; }
        public decimal ActiveImportEnergy { get; set; }
        public decimal ActiveExportEnergy { get; set; }
        public decimal ReactiveImportEnergy { get; set; }
        public decimal ReactiveExportEnergy { get; set; }
    
        public virtual ICollection<AMS_RishMaster_Group> AMS_RishMaster_Group { get; set; }
        public virtual ICollection<DemoUnit_Event> DemoUnit_Event { get; set; }
        public virtual ICollection<MyAppsDemoEvent> MyAppsDemoEvents { get; set; }
    }
}
