//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBForTestingEntities : DbContext
    {
        public DBForTestingEntities()
            : base("name=DBForTestingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AMS_Event> AMS_Event { get; set; }
        public virtual DbSet<AMS_Event_Daily> AMS_Event_Daily { get; set; }
        public virtual DbSet<AMS_Event_Latest> AMS_Event_Latest { get; set; }
        public virtual DbSet<AMS_RishMaster_Group> AMS_RishMaster_Group { get; set; }
        public virtual DbSet<DemoUnit_Event> DemoUnit_Event { get; set; }
        public virtual DbSet<DemoUnit_LatestEvent> DemoUnit_LatestEvent { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<GPSDevice> GPSDevices { get; set; }
        public virtual DbSet<GPSDevice_Event> GPSDevice_Event { get; set; }
        public virtual DbSet<GPSDevice_LatestEvent> GPSDevice_LatestEvent { get; set; }
        public virtual DbSet<LatestEvent> LatestEvents { get; set; }
        public virtual DbSet<MyAppsDemoEvent> MyAppsDemoEvents { get; set; }
        public virtual DbSet<MyAppsDemoEvent_Latest> MyAppsDemoEvent_Latest { get; set; }
        public virtual DbSet<RishMasterEvent> RishMasterEvents { get; set; }
    }
}
